INSERT INTO room (name) VALUES ('A')
INSERT INTO room (name) VALUES ('B')
INSERT INTO room (name) VALUES ('C')
INSERT INTO room (name) VALUES ('D')
INSERT INTO room (name) VALUES ('E')
INSERT INTO room (name) VALUES ('F')
INSERT INTO room (name) VALUES ('G')

INSERT INTO emp(emp_no, name) VALUES (0, 'vince')
INSERT INTO emp(emp_no, name) VALUES (1, 'donny')
INSERT INTO emp(emp_no, name) VALUES (2, 'dan')

INSERT INTO reservation(slot_no, date, room_no, emp_no) VALUES (1, '2018-07-01', 1, 2)
INSERT INTO reservation(slot_no, date, room_no, emp_no) VALUES (2, '2018-07-02', 2, 0)
INSERT INTO reservation(slot_no, date, room_no, emp_no) VALUES (3, '2018-07-03', 3, 1)
INSERT INTO reservation(slot_no, date, room_no, emp_no) VALUES (4, '2018-07-04', 4, 2)
INSERT INTO reservation(slot_no, date, room_no, emp_no) VALUES (5, '2018-07-05', 5, 0)